#!/bin/bash

/usr/bin/rsync --verbose --progress --stats --compress -e "ssh -i $KEY" --recursive --times --perms --links --delete --exclude ".gvfs" --exclude ".cache" --exclude ".local" --exclude "tmp" --exclude ".VirtualBox" $LOCAL $REMOTE
